import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.comunicacion.*
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoGarvisCognitivo.objetivos.*;
import icaro.aplicaciones.informacion.gestionGarvis.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoGarvisCognitivo.tareas.*;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;
//=======================================================================
rule "Creacion de los objectivos iniciales"
when
  //not(Focus())
then 
  TareaSincrona tarea = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
  tarea.ejecutar();
  recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
  //EncenderTele et = new EncenderTele();
  //insert(et);
end

// =======================================================================

//Reglas de focalizacion.
rule "Regla de focalizacion en objetivo AutorizarAccesoUsuarios"
 when
    f:Focus(foco == null )
    obj:ObtenerInfoInterlocutor()
 then
    f.setFoco(obj);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    update(f);
end
//=======================================================================


///Reglas de Consecucion del Objetivo ObtenerInfoInterlocutor
rule "Inicio del proceso de consecucion del  objetivo ObtenerInfoInterlocutor"
  when
    obj:ObtenerInfoInterlocutor(state==Objetivo.PENDING)
    Focus(foco ==obj)
  then
    obj.setSolving();
    update(obj);
end

rule "Saludo Inicial y peticion de info"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
   then
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Se ejecuta la tarea : SolicitarDatosAcceso",InfoTraza.NivelTraza.debug));
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicial.class);
     tarea.ejecutar(VocabularioGeneralGarvis.IdentRecursoComunicacionChat);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Saludo Respuesta al interlocutor y peticion de datos iniciales "
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionSaludo)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SaludarYPresentarFuncionalidad.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

/********************************REGLA DESPEDIDA*******************************************************/


rule "Despedida Garvis"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionDespedida)
   then
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(DespedidaGarvis.class);
    tarea.ejecutar(identInterlc);
end

/*****************************************************************************************************/

rule "No hay extraccion  semantica del texto del interlocutor "
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    SintonizaTV(state==Objetivo.PENDING)
    EncenderMicro(state==Objetivo.PENDING)
    AddLibro(state==Objetivo.PENDING)
    obj1:EncenderTele();
    notif:Notificacion(identInterlc:identNotificador, (tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAfirmacion || tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionNegacion || tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull))
   then
   	 obj1.sumContarPeticion();
   	 update(obj1);
   	 retract(notif);
   	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicialCita.class);
     tarea.ejecutar(identInterlc,VocabularioGeneralGarvis.preambuloNoHeEntendido,VocabularioGeneralGarvis.peticionInfoIicialCita1 );
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "No entiendo lo que dices 1"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    SintonizaTV(state==Objetivo.PENDING)
    EncenderMicro(state==Objetivo.PENDING)
    obj1:EncenderTele(getContarPeticion()==1);
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull)
   then
   	 obj1.sumContarPeticion();
   	 update(obj1);
   	 retract(notif);
   	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicialCita.class);
     tarea.ejecutar(identInterlc,VocabularioGeneralGarvis.RespuestaNoEniendo1,VocabularioGeneralGarvis.peticionInfoIicialCita1  );
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
rule "No entiendo lo que dices 2"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    SintonizaTV(state==Objetivo.PENDING)
    EncenderMicro(state==Objetivo.PENDING)
    obj1:EncenderTele(getContarPeticion()==2);
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull)
   then
   	 obj1.sumContarPeticion();
   	 update(obj1);
   	 retract(notif);
   	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicialCita.class);
     tarea.ejecutar(identInterlc,VocabularioGeneralGarvis.RespuestaNoEniendo2,VocabularioGeneralGarvis.peticionInfoIicialCita1  );
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
rule "No entiendo lo que dices 3"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    SintonizaTV(state==Objetivo.PENDING)
    EncenderMicro(state==Objetivo.PENDING)
    obj1:EncenderTele(getContarPeticion()==3);
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull)
   then
   	 obj1.setContarPeticion(0);
   	 update(obj1);
   	 retract(notif);
   	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicialCita.class);
     tarea.ejecutar(identInterlc,VocabularioGeneralGarvis.RespuestaNoEniendo3,"");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Estas hablando de mi "
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionGarvis)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaGarvis.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la nevera"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionNevera)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaNevera.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

/* *********************************REGLAS PARA MICROONDAS************************************ */

/*rule "Mencionaste Meter comida en Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:MeterComidaMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAlimentos)
   then
   	obj1.setSolved();
   	update(obj1);
   	String alimento = notif.getMensajeNotificacion();
   	retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
    tarea.ejecutar(identInterlc,"Has metido alimento",alimento);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end*/

rule "Mencionaste Encender Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.PENDING)
   	obj2:ApagarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncendermicro)
   then
   	obj1.setSolving();
   	update(obj1);
   	obj2.setSolving();
    update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He encendido el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Pide el tiempo de encendido del microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.SOLVING)
   	obj2:ApagarMicro(state==Objetivo.SOLVING)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar("","Cuanto tiempo deseas activar el microondas?");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Ingresó el tiempo de encendido del microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.SOLVING)
   	obj2:ApagarMicro(state==Objetivo.SOLVING)
   	notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionTiempoMicro)
   then
   	 String tiempo = notif.getMensajeNotificacion();
     obj1.setSolved();
     update(obj1);
   	 retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar("","He puesto el microondas "+tiempo);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Indicar que terminó el tiempo del microondas y apagarlo"
    timer (cron:* 0/5 * * * ?)
when
    //$a : Alarm( on == true )
    obj1:EncenderMicro(state==Objetivo.SOLVED)
   	obj2:ApagarMicro(state==Objetivo.SOLVING)
then
	obj1.setPending();
   	update(obj1);
   	obj2.setPending();
   	update(obj2);
   	TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
    tarea.ejecutar("","Ha terminado el tiempo de encendido del microondas. Tu comida está lista. He apagado el microondas.");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "No ingresa el tiempo de encendido del microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.SOLVING)
   	obj2:ApagarMicro(state==Objetivo.SOLVING)
   	notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull)
   then
   	 retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar("","Por favor ingresa el tiempo para el microondas");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule " Volviste ha Mencionar Encender Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:ApagarMicro(state==Objetivo.SOLVING)
    obj2:EncenderMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncendermicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuenctra encendido el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule "Mencionaste Apagar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:ApagarMicro(state==Objetivo.SOLVING)
    obj2:EncenderMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarmicro)
   then
   	obj1.setPending();
   	update(obj1);
   	obj2.setPending();
   	update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He apagado el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Volviste ah Mencionar Apagar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.PENDING)
   	obj2:ApagarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarmicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuentra apagado el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule "Mencionaste Abrir Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:AbrirMicro(state==Objetivo.PENDING)
   	obj2:CerrarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAbrirmicro)
   then
   	obj1.setSolved();
   	update(obj1);
   	obj2.setSolving();
    update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He abierto la Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule " Volvistes ah Mencionar Abrir Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:CerrarMicro(state==Objetivo.SOLVING)
    obj2:AbrirMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAbrirmicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuenctra abierto la puerta del Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule "Mencionaste Cerrar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:CerrarMicro(state==Objetivo.SOLVING)
    obj2:AbrirMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionCerrarmicro)
   then
   	obj1.setPending();
   	update(obj1);
   	obj2.setPending();
   	update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He Cerrado la Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Volviste ah Mencionar Cerrar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:AbrirMicro(state==Objetivo.PENDING)
   	obj2:CerrarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionCerrarmicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuentra cerrado la puerta del Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


/*rule "Mencionaste la microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionMicroondas)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end*/

/* *********************************************************************************************** */

//============Reglas Biblioteca============================
//---------------------------------------
rule "Solicitud Añadir Libro"
when 
	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
	notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNotificacionPedirLibro)
	obj1:AddLibro(state==Objetivo.PENDING)
then
	obj1.setSolving();
	update(obj1);
	retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaBiblioteca.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Añadir Libro"
when
	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
	notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionLibro)
	obj1:AddLibro(state==Objetivo.SOLVING)
then
	retract(notif);
	String libro = notif.getMensajeNotificacion();
	TareaSincrona tarea = gestorTareas.crearTareaSincrona(ObtenerLibros.class);
     tarea.ejecutar(identInterlc,libro,"1");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "No identifica libro"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull)
   	obj1:AddLibro(state==Objetivo.SOLVING)
   then
   	//obj1.setPending();
   	//update(obj1);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(NoIdentificaLibro.class);
     tarea.ejecutar(identInterlc);
     retract(notif);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "No desea añadir nuevo libro"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionNegacion)
   	obj1:AddLibro(state==Objetivo.SOLVING)
   then
   	obj1.setPending();
	update(obj1);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(DespedidaGarvis.class);
     tarea.ejecutar(identInterlc);
     retract(notif);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Si desea añadir nuevo libro"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAfirmacion)
   	obj1:AddLibro(state==Objetivo.SOLVING)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaBiblioteca.class);
     tarea.ejecutar(identInterlc);
     retract(notif);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Quiero Leer un libro"
when
	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionLectura)
   	obj1:AddLibro(state==Objetivo.PENDING)
   	obj2:LeerLibro(state==Objetivo.PENDING)
then
	obj2.setSolving();
	update(obj2);
	TareaSincrona tarea = gestorTareas.crearTareaSincrona(ConsultaLibro.class);
    tarea.ejecutar(identInterlc);
    retract(notif);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Indicar Libro a Consultar"
when
	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionLibro)
   	obj1:LeerLibro(state==Objetivo.SOLVING)
then
	obj1.setPending();
	update(obj1);
	String libron = notif.getMensajeNotificacion();
	TareaSincrona tarea = gestorTareas.crearTareaSincrona(ObtenerLibros.class);
    tarea.ejecutar(identInterlc,libron,"2");
    retract(notif);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

//---------------------------------------
rule "Mencionaste la Dispensador"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionDispensador)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaDispensador.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Aspiradora"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAspiradora)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaAspiradora.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Termostato"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionTermostato)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTermostato.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Detector"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionDetector)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaDetector.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


//============Reglas Tv============================
//---------------------------------------
rule "Mencionaste la television para grabar programa"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
	obj1:EncenderTele(state==Objetivo.SOLVED)
    obj2:GrabarProgramaTV(state==Objetivo.SOLVING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionGrabarTV)
   then
    obj2.setSolving();
    update(obj2);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Estoy grabando...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
//---------------------------------------
rule "Mencionaste la television para sintonizar"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
	obj1:EncenderTele(state==Objetivo.SOLVED)
    obj2:SintonizaTV(state==Objetivo.REFINED || state==Objetivo.SOLVING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionSintonizaTV)
   then
    obj2.setSolving();
    update(obj2);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Listo ya tienes tu programa, disfrútalo...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
//---------------------------------------
rule "Mencionaste la television para encender"
activation-group "encender-tv"
salience 200
   when
	obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    obj3:SintonizaTV(state==Objetivo.PENDING)
    obj4:GrabarProgramaTV(state==Objetivo.PENDING)
    obj5:ApagarTele(state==Objetivo.PENDING || state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncenderTV)
   then
    obj2.setSolved();
    update(obj2);
    obj3.setSolving();//obj3 listo para sintonizar
    update(obj3);
    obj4.setSolving();//obj4 listo para grabar
    update(obj4);
    obj5.setPending();//Apagar activo
    update(obj5);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"TV en ON");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la television para apagar"
   when
    obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.SOLVED)
    obj3:ApagarTele(state==Objetivo.PENDING)
    obj4:SintonizaTV(state==Objetivo.SOLVING || state==Objetivo.REFINED)//Sintonizar esta activo ya que la TV está encendida
    obj5:GrabarProgramaTV(state==Objetivo.SOLVING)//Grabar esta activo ya que la TV está encendida
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarTV)
   then
   	obj3.setSolved();
   	update(obj3);
    obj2.setPending();
    update(obj2);
    obj4.setPending();//Sintonizar se desactiva
    update(obj4);
    obj5.setPending();//Grabar se desactiva
    update(obj5);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"TV en OFF");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
rule "Volviste a mencionar la television para apagar"
   when
	obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    obj3:SintonizaTV(state==Objetivo.PENDING)
    obj4:GrabarProgramaTV(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarTV)
   then
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Ya tienes la TV apagada!...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Volviste a Mencionar la television para encender"
   when
    obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.SOLVED)
    obj3:ApagarTele(state==Objetivo.PENDING)
    obj4:SintonizaTV(state==Objetivo.SOLVING)//Sintonizar esta activo ya que la TV está encendida
    obj5:GrabarProgramaTV(state==Objetivo.SOLVING)//Grabar esta activo ya que la TV está encendida
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncenderTV)
   then
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Ya tienes la TV encendida!...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la television para grabar pero está apagada"
   when
    obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionGrabarTV)
    flg:EncenderTele(isFlag1()==false)//Flag para grabar
   then
   	flg.Cambiarflag1();//Cambiar el valor del flag
   	update(flg);
   	retract(notif);
   	TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Tienes la TV apaga! No puedo grabar tu programa");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la television para sintonizar pero está apagada"
   when
    obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    flg:EncenderTele(isFlag()==false)//Flag para sintonizar
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionSintonizaTV)
   then
   	flg.Cambiarflag();
   	update(flg);
   	retract(notif);
   	TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Tienes la TV apaga! No puedo sintonizar ningún canal");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Encender TV porque dijo sintonizar"
   when
	obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    obj3:SintonizaTV(state==Objetivo.PENDING)
    obj4:GrabarProgramaTV(state==Objetivo.PENDING)
    flg:EncenderTele(isFlag()==true)//Flag para sintonizar
   then
   	flg.Cambiarflag();//Cambiar el valor del flag
   	update(flg);
    obj2.setSolved();
    update(obj2);
    obj3.setRefined();//obj3 listo para sintonizar
    update(obj3);
    obj4.setSolving();//obj4 listo para grabar
    update(obj4);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar("Tony","He encendido la TV por ti...Qué canal deseas?");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Encender TV porque dijo grabar"
   when
	obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    obj3:SintonizaTV(state==Objetivo.PENDING)
    obj4:GrabarProgramaTV(state==Objetivo.PENDING)
    flg:EncenderTele(isFlag1()==true)//Flag para sintonizar
   then
   	flg.Cambiarflag1();//Cambiar el valor del flag
   	update(flg);
    obj2.setSolved();
    update(obj2);
    obj3.setSolving();//obj3 listo para sintonizar
    update(obj3);
    obj4.setSolving();//obj4 listo para grabar
    update(obj4);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar("Tony","He encendido la TV por ti ¿Qué programa deseas grabar?");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
rule "El usuario no ingresa el canal a sintonizar"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj2:SintonizaTV(state==Objetivo.REFINED)
    ct:EncenderTele(getContarPeticion()<3);
    notif:Notificacion(identInterlc:identNotificador, (tipoNotificacion!=VocabularioGeneralGarvis.NombreTipoNoticacionSintonizaTV && tipoNotificacion!=VocabularioGeneralGarvis.NombreTipoNoticacionApagarTV && tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull) )
   then
    ct.sumContarPeticion();//Actualiza los intentos fallidos
    update(ct);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Aun no me has dicho que canal sintonizar. Cual deseas?");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Ha pedido 3 veces el canal y no ha habido repsuesta apago la TV"
   when
    obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.SOLVED)
    obj3:ApagarTele(state==Objetivo.PENDING)
    obj4:SintonizaTV(state==Objetivo.SOLVING || state==Objetivo.REFINED)//Sintonizar esta activo ya que la TV está encendida
    obj5:GrabarProgramaTV(state==Objetivo.SOLVING)//Grabar esta activo ya que la TV está encendida
    ct:EncenderTele(getContarPeticion()==3)
   then
    ct.setContarPeticion(0);
    update(ct);
   	obj3.setSolved();
   	update(obj3);
    obj2.setPending();
    update(obj2);
    obj4.setPending();//Sintonizar se desactiva
    update(obj4);
    obj5.setPending();//Grabar se desactiva
    update(obj5);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar("","No he podido entender tu orden para sintonizar. Apagaré la TV");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste un canal"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderTele(state==Objetivo.SOLVED)
    obj2:SintonizaTV(state==Objetivo.REFINED || state==Objetivo.SOLVING)
    ct:EncenderTele(getContarPeticion()<3);
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionCanal )
   then
    String canal = notif.getMensajeNotificacion(); 
    obj2.setSolving();
    update(obj2);
    ct.setContarPeticion(0);
    update(ct);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"He sintonizado "+canal);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste un canal cuando TV apagada"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderTele(state==Objetivo.PENDING)
    obj2:SintonizaTV(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionCanal )
   then
    String canal = notif.getMensajeNotificacion(); 
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Entiendo que quieres sintonizar "+canal+". Te sugiero encender la TV.");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
rule "Mencionaste solo la TV"
activation-group "encender-tv"
salience -10
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderTele(state==Objetivo.PENDING)
    obj2:ApagarTele(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionTelevision)
   then
    String tv = notif.getMensajeNotificacion(); 
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Entiendo que quieres interactuar con la "+tv+". Te sugiero que la enciendas");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end