import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.comunicacion.*
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoGarvisCognitivo.objetivos.*;
import icaro.aplicaciones.informacion.gestionGarvis.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoGarvisCognitivo.tareas.*;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;

//=======================================================================
rule "Creacion de los objectivos iniciales"
when
  //not(Focus())
then 
  TareaSincrona tarea = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
  tarea.ejecutar();
  recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
  //EncenderTele et = new EncenderTele();
  //insert(et);
end

// =======================================================================

//Reglas de focalizacion.
rule "Regla de focalizacion en objetivo AutorizarAccesoUsuarios"
 when
    f:Focus(foco == null )
    obj:ObtenerInfoInterlocutor()
 then
    f.setFoco(obj);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    update(f);
end
//=======================================================================
///Reglas de Consecucion del Objetivo ObtenerInfoInterlocutor
rule "Inicio del proceso de consecucion del  objetivo ObtenerInfoInterlocutor"
  when
    obj:ObtenerInfoInterlocutor(state==Objetivo.PENDING)
    Focus(foco ==obj)
  then
    obj.setSolving();
    update(obj);
end
rule "Saludo Inicial y peticion de info"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
   then
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Se ejecuta la tarea : SolicitarDatosAcceso",InfoTraza.NivelTraza.debug));
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicial.class);
     tarea.ejecutar(VocabularioGeneralGarvis.IdentRecursoComunicacionChat);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Saludo Respuesta al interlocutor y peticion de datos iniciales "
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionSaludo)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SaludarYPresentarFuncionalidad.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
rule "No hay extraccion  semantica del texto del interlocutor  "
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.ExtraccionSemanticaNull)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarInfoInicialCita.class);
     tarea.ejecutar(identInterlc,VocabularioGeneralGarvis.preambuloNoHeEntendido,VocabularioGeneralGarvis.peticionInfoIicialCita1  );
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Estas hablando de mi "
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionGarvis)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaGarvis.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la nevera"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionNevera)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaNevera.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

/* *********************************REGLAS PARA MICROONDAS************************************ */

rule "Mencionaste Encender Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.PENDING)
   	obj2:ApagarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncendermicro)
   then
   	obj1.setSolved();
   	update(obj1);
   	obj2.setSolving();
    update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He encendido el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule " Volvistes ah Mencionar Encender Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:ApagarMicro(state==Objetivo.SOLVING)
    obj2:EncenderMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncendermicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuenctra encendido el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule "Mencionaste Apagar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:ApagarMicro(state==Objetivo.SOLVING)
    obj2:EncenderMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarmicro)
   then
   	obj1.setPending();
   	update(obj1);
   	obj2.setPending();
   	update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He apagado el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Volviste ah Mencionar Apagar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:EncenderMicro(state==Objetivo.PENDING)
   	obj2:ApagarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarmicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuentra apagado el Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule "Mencionaste Abrir Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:AbrirMicro(state==Objetivo.PENDING)
   	obj2:CerrarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAbrirmicro)
   then
   	obj1.setSolved();
   	update(obj1);
   	obj2.setSolving();
    update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He abierto la Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule " Volvistes ah Mencionar Abrir Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:CerrarMicro(state==Objetivo.SOLVING)
    obj2:AbrirMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAbrirmicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuenctra abierto la puerta del Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


rule "Mencionaste Cerrar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:CerrarMicro(state==Objetivo.SOLVING)
    obj2:AbrirMicro(state==Objetivo.SOLVED)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionCerrarmicro)
   then
   	obj1.setPending();
   	update(obj1);
   	obj2.setPending();
   	update(obj2);
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"He Cerrado la Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Volviste ah Mencionar Cerrar Microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    obj1:AbrirMicro(state==Objetivo.PENDING)
   	obj2:CerrarMicro(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionCerrarmicro)
   then
   	retract(notif);
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc,"Ya se encuentra cerrado la puerta del Microondas...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj1.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end


/*rule "Mencionaste la microondas"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionMicroondas)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end*/

/* *********************************************************************************************** */

rule "Mencionaste la television para grabar programa"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
	obj1:EncenderTele(state==Objetivo.SOLVED)
    obj2:GrabarProgramaTV(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionGrabarTV)
   then
    obj2.setSolving();
    update(obj2);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Estoy grando...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
//---------------------------------------
rule "Mencionaste la television para sintonizar"
   when
   	obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
	obj1:EncenderTele(state==Objetivo.SOLVED)
    obj2:SintonizaTV(state==Objetivo.SOLVING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionSintonizaTV)
   then
    //obj2.setSolving();
    //update(obj2);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"Listo ya tienes tu programa, disfrútalo...");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end
//---------------------------------------
rule "Mencionaste la television para encender"
   when
	obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.PENDING)
    obj3:SintonizaTV(state==Objetivo.PENDING)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionEncenderTV)
   then
    obj2.setSolved();
    update(obj2);
    obj3.setSolving();//obj3 listo para sintonizar
    update(obj3);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"TV en ON");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la television para apagar"
   when
    obj1:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj1)
    obj2:EncenderTele(state==Objetivo.SOLVED)
    obj3:ApagarTele(state==Objetivo.PENDING)
    obj4:SintonizaTV(state==Objetivo.SOLVING)//Sintonizar esta activo ya que la TV está encendida
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionApagarTV)
   then
   	obj3.setSolved();
   	update(obj3);
    obj2.setPending();
    update(obj2);
    obj4.setPending();//Sintonizar se desactiva
    update(obj4);
    retract(notif);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTelevision.class);
    tarea.ejecutar(identInterlc,"TV en OFF");
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj2.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la biblioteca"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionBiblioteca)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaBiblioteca.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Dispensador"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionDispensador)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaDispensador.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Aspiradora"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionAspiradora)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaAspiradora.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Termostato"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionTermostato)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaTermostato.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste la Detector"
   when
    obj:ObtenerInfoInterlocutor(state==Objetivo.SOLVING)
    Focus(foco == obj)
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionDetector)
   then
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaDetector.class);
     tarea.ejecutar(identInterlc);
    recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Mencionaste listar libro"
   when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion==VocabularioGeneralGarvis.NombreTipoNoticacionListarLibro , msgg:mensajeNotificacion)
    libro:IdentificarLibro(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    obj:AddLibro(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    //Focus(foco == obj)
   then
   	libro.setSolved();
   	obj.SumarLibro(msgg);
	TareaSincrona tarea = gestorTareas.crearTareaSincrona(RespuestaMicroondas.class);
    tarea.ejecutar(identInterlc,VocabularioGeneralGarvis.msglibro);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
 	update(libro);
    retract(notif);
end







